language: java
addons:
  sonarcloud:
    organization: "mishauni13-github"
    token:
      secure: a74ab65620a5dec28ac81666333ada287437c439
    branches:
      - master
script:
  # other script steps might be done before running the actual analysis
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
