language: java
addons:
  sonarcloud:
    organization: "mishauni13-github"
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - master
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
